### ISSUE TITLE
1.1.4 gives assert failure message on quit / 1.1.5 fails to start

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#9]
Here is a bug scenario on version 1.14 (_1.15 can't start_):
Open the application
Click on the cross to close the window. The following error message displays:
![quitbug](https://cloud.githubusercontent.com/assets/22278738/23969642/6c7dd95a-09c7-11e7-94a0-46c95951812d.png)

I'm using Windows 7 Pro.

**Comment by chelh** [comment]
The bug you've reported in 1.1.4 seems to be an issue with asking .Net Framework 4.0 to access isolated storage in a thread that is set to a non–US English culture. I have a workaround, but it's an ugly one.

I've used 1.1.5 on another computer and confirmed that it failed to start on that one. Currently trying to find out what's going on…

**Comment by hectorticoli** [comment]
I would guess that this is related to your recent change of compilation options (remove pdb). I'd try to revert this specific commit as a beginning.

**Comment by chelh** [comment]
Could you please try this new version, to see that this bug is fixed and your translation shows up?
[VBA.Sync.Tool-v1.1.6.zip](https://github.com/chelh/VBASync/files/855013/VBA.Sync.Tool-v1.1.6.zip)

**Comment by hectorticoli** [comment]
Okay, I test on the 2 computers where I noticed the bug and I'll let you know.

**Comment by hectorticoli** [comment]
Bad news, I still have the assert failure, and the news is that avast pointed the application as "rare", and as a type that usually contains viruses. I'm pretty sure there's no virus, but the trick made avast nervous. I'll let you know if avast gives me a specific feedback about the file. NB: The assert failure occured when avast was deactivated.

**Comment by hectorticoli** [comment]
![stacktraceerror](https://cloud.githubusercontent.com/assets/22278738/24121875/1cf5d80a-0dba-11e7-9ffd-abb5cb907386.png)
The stackTrace of the error with version 1.1.6, maybe that will help.

**Comment by chelh** [comment]
Give this one a try please. It puts into place a rather ugly hack, but should fix your issue.

[VBA.Sync.Tool-v1.1.6b.zip](https://github.com/chelh/VBASync/files/857022/VBA.Sync.Tool-v1.1.6b.zip)

**Comment by hectorticoli** [comment]
I don't get the error anymore on my computer with the described scenario. I will test on another computer where I faced the issue to confirm that this is fixed.

If the hack is ugly, maybe you'll come with a nicer fix in a near future ^^

I'll let you know ASAP (probably tomorrow)

**Comment by hectorticoli** [comment]
Okay, the version works on the other computer too. I consider the issue as solved on version 1.1.6b, so maybe you can generate a version 1.1.7 with the translation update^^

**Comment by chelh** [comment]
The next release will be v1.2.0, and it's slated to have the following:

  * A better fix for this issue (save `LastSession.ini` directly in `%AppData%`, not isolated storage)
  * The fix I've already put into place for #10 
  * More command-line parameters (to satisfy #5)
  * Your French translation (after I've done a fairly thorough sweep to detect more localizable strings)
  * A language switcher in the Options window, and code to auto-open the Options menu on first run
  * A multi-language installer/uninstaller package (Inno Setup)

**Comment by hectorticoli** [comment]
> A multi-language installer/uninstaller package (Inno Setup)

If possible, I'd be interested with a portable version (like now) too

**Comment by chelh** [comment]
Fixed in release 1.2.0
